[build]
  commands = [
    "apt-get update && apt-get install -y curl php-cli php-mbstring unzip git",
    "curl -sS https://getcomposer.org/installer | php",
    "mv composer.phar /usr/local/bin/composer",
    "npm install -g npm",
    "composer install",
    "npm i",
    "npm run build",
    "php artisan migrate --force",
    "php artisan optimize",
    "chmod 777 -R storage/",
    "chmod 777 -R bootstrap/cache",
    "php artisan storage:link"
  ]

[start]
  command = "php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
